### ISSUE TITLE
undefined method `sysctl' for cookbook: os-hardening

### ISSUE THREAD

**Issue by oneandoneis2** [dev-sec/chef-os-hardening#253]
**Describe the bug**
A cookbook that was working perfectly before is now erroring due to its os-hardening dependency

**Expected behavior**
There should be no "method undefined" errors

**Actual behavior**

```paste below
    amazon-ebs: Recipe Compile Error in /tmp/packer-chef-client/local-mode-cache/cache/cookbooks/uj_hardening/recipes/default.rb
    amazon-ebs: ================================================================================
    amazon-ebs:
    amazon-ebs: NoMethodError
    amazon-ebs: -------------
    amazon-ebs: undefined method `sysctl' for cookbook: os-hardening, recipe: sysctl :Chef::Recipe
    amazon-ebs:
    amazon-ebs: Cookbook Trace:
    amazon-ebs: ---------------
    amazon-ebs: /tmp/packer-chef-client/local-mode-cache/cache/cookbooks/os-hardening/recipes/sysctl.rb:133:in `block in from_file'
    amazon-ebs: /tmp/packer-chef-client/local-mode-cache/cache/cookbooks/os-hardening/recipes/sysctl.rb:131:in `each'
    amazon-ebs: /tmp/packer-chef-client/local-mode-cache/cache/cookbooks/os-hardening/recipes/sysctl.rb:131:in `from_file'
    amazon-ebs: /tmp/packer-chef-client/local-mode-cache/cache/cookbooks/os-hardening/recipes/default.rb:44:in `block in from_file'
    amazon-ebs: /tmp/packer-chef-client/local-mode-cache/cache/cookbooks/os-hardening/recipes/default.rb:43:in `each'
    amazon-ebs: /tmp/packer-chef-client/local-mode-cache/cache/cookbooks/os-hardening/recipes/default.rb:43:in `from_file'
    amazon-ebs: /tmp/packer-chef-client/local-mode-cache/cache/cookbooks/uj_hardening/recipes/default.rb:7:in `from_file'
    amazon-ebs:
    amazon-ebs: Relevant File Content:
    amazon-ebs: ----------------------
    amazon-ebs: /tmp/packer-chef-client/local-mode-cache/cache/cookbooks/os-hardening/recipes/sysctl.rb:
    amazon-ebs:
    amazon-ebs: 126:  # may contain sensitive information.
    amazon-ebs: 127:  node.default['sysctl']['params']['fs']['suid_dumpable'] =
    amazon-ebs: 128:    node['os-hardening']['security']['kernel']['enable_core_dump'] ? 2 : 0
    amazon-ebs: 129:
    amazon-ebs: 130:  if node.attribute?('sysctl') && node['sysctl'].attribute?('params')
    amazon-ebs: 131:    coerce_attributes(node['sysctl']['params']).each do |x|
    amazon-ebs: 132:      k, v = x.split('=')
    amazon-ebs: 133>>     sysctl k do
    amazon-ebs: 134:        value v
    amazon-ebs: 135:      end
    amazon-ebs: 136:    end
    amazon-ebs: 137:  end
    amazon-ebs: 138:
    amazon-ebs: 139:  # try to determine the real cpu vendor
    amazon-ebs: 140:  begin
    amazon-ebs: 141:    cpu_vendor = node['cpu']['0']['vendor_id'].
    amazon-ebs: 142:                 sub(/^.*GenuineIntel.*$/, 'intel').
    amazon-ebs:
    amazon-ebs: System Info:
    amazon-ebs: ------------
    amazon-ebs: chef_version=13.8.5
    amazon-ebs: platform=ubuntu
    amazon-ebs: platform_version=18.04
    amazon-ebs: ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
    amazon-ebs: program_name=chef-client worker: ppid=1587;start=13:24:54;
    amazon-ebs: executable=/opt/chef/bin/chef-client

```

**OS / Environment**

Ubuntu 18.04

**Chef Version**

```paste below
$ chef -v
Chef Workstation: 0.2.43
  chef-run: 0.2.4
  chef-client: 14.8.12
  delivery-cli: master (5fb4908da53579c9dcf4894d4acf94d2d9ee6475)
  berks: 7.0.7
  test-kitchen: 1.24.0
  inspec: 3.2.6

```

**Cookbook Version**

```paste below
4.0.0
```

**Additional context**

**Comment by artem-sidorenko** [comment]
@oneandoneis2 thanks for raising the issue. We switched to the sysctl implementation of chef in #228. This is leading to the issue on your side. I'll have a look. As a workaround for now you can pin the cookbook to the major version 3 on your side, like

```ruby
# metadata.rb

depends 'chef-os-hardening', '~> 3.2.1'
```

**Comment by artem-sidorenko** [comment]
@oneandoneis2 is `chef -v` maybe from your development system? I see in your packer output chef 13:

```
    amazon-ebs: System Info:
    amazon-ebs: ------------
    amazon-ebs: chef_version=13.8.5           <----------------------------------------
    amazon-ebs: platform=ubuntu
    amazon-ebs: platform_version=18.04
    amazon-ebs: ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
    amazon-ebs: program_name=chef-client worker: ppid=1587;start=13:24:54;
    amazon-ebs: executable=/opt/chef/bin/chef-client
```

Chef 13 is EOL already for a while, with chef-os-hardening 4.0.0 we dropped the support of chef 13.

If you want to continue using chef 13, you should pin the cookbook version like in the example above.

**Comment by oneandoneis2** [comment]
Thanks for the quick replies!

Pinning to the previous version does indeed fix things for now. I'd missed that packer was still running the v13 chef - guess it's time to write up an upgrade ticket!

Cheers!
