### ISSUE TITLE
Procps conditional failing

### ISSUE THREAD

**Issue by arlimus** [dev-sec/chef-os-hardening#48]
I only noticed this on a Ubuntu server 14.04 with chef 11.16.0. This is from a chef-solo run:

```
    ================================================================================
    Error executing action `start` on resource 'service[procps]'
    ================================================================================

    ArgumentError
    -------------
    wrong number of arguments (2 for 0)

    Cookbook Trace:
    ---------------
    /chef/cookbooks-2/os-hardening/recipes/sysctl.rb:88:in `block (2 levels) in from_file'

    Resource Declaration:
    ---------------------
    # In /chef/cookbooks-2/os-hardening/recipes/sysctl.rb

     84:   service 'procps' do
     85:     provider service_provider
     86:     supports restart: false, reload: false
     87:     action [:enable, :start]
     88:     only_if { cookbook_version('sysctl', '< 0.6.0') }
     89:   end
     90: end

    Compiled Resource:
    ------------------
    # Declared in /chef/cookbooks-2/os-hardening/recipes/sysctl.rb:84:in `from_file'

    service("procps") do
      provider Chef::Provider::Service::Upstart
      action [:enable, :start]
      supports {:restart=>false, :reload=>false}
      retries 0
      retry_delay 2
      guard_interpreter :default
      service_name "procps"
      pattern "procps"
      cookbook_name :"os-hardening"
      recipe_name "sysctl"
      only_if { #code block }
    end
```

**Comment by artem-sidorenko** [comment]
The problem is somewhere on the line 88, where we had a sysctl version expression. As we do not have it anymore, I do not think this issue is still there. Feel free to reopen if needed
